name: woju
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  accessibility_tools: ^2.2.1
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_onboarding_slider: ^1.0.11
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl_phone_number_input: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
