name: woju
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  accessibility_tools: ^2.2.1
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.2
  easy_localization: ^3.0.7
  firebase_auth: ^4.20.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.1
  flutter_onboarding_slider: ^1.0.11
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^4.2.1
  fluttertoast: ^8.2.6
  go_router: ^14.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  modal_bottom_sheet: ^3.0.0
  scroll_date_picker: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/translations/
    - assets/images/
